apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: strimzi-drain-cleaner
  labels:
    app: strimzi-drain-cleaner
  namespace: kafka-operator
spec:
  secretName: strimzi-drain-cleaner
  commonName: strimzi-drain-cleaner
  dnsNames:
    - strimzi-drain-cleaner.kafka-operator.svc
    - strimzi-drain-cleaner.kafka-operator
    - strimzi-drain-cleaner
  issuerRef:
    name: strimzi-drain-cleaner
