apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: replicator
  namespace: flux-system
spec:
  dependsOn:
    - name: flux-system
  interval: 10m0s
  path: ./manifests/replicator
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
