apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: linkerd-control-plane
      version: '1.12.6'
      sourceRef:
        kind: HelmRepository
        name: linkerd
        namespace: flux-system
      interval: 1m
  targetNamespace: linkerd
  values:
    identity:
      issuer:
        scheme: kubernetes.io/tls
  valuesFrom:
    - kind: Secret
      name: linkerd-identity-issuer
      valuesKey: ca.crt
      targetPath: identityTrustAnchorsPEM
