apiVersion: apps/v1
kind: Deployment
metadata:
  name: dac-crds-update-denied
  namespace: default
  labels:
    app: dac-crds-update-denied
  annotations:
    reloader.stakater.com/auto: true
    secret.reloader.stakater.com/reload: dac-crds-update-denied
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dac-crds-update-denied
  template:
    metadata:
      labels:
        app: dac-crds-update-denied
    spec:
      containers:
        - name: server
          image: registry.localhost:5000/dac:0.1.0
          imagePullPolicy: Always
          env:
            - name: ALLOWED
              value: "${ALLOWED:=false}"
          ports:
            - containerPort: 443
              name: https
            - containerPort: 3000
              name: http
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - name: tls-certs
              mountPath: /work/certs
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: dac-crds-update-denied
