apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkerd
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 10m0s
  path: ./manifests/linkerd
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  patches:
    - patch: |-
        apiVersion: helm.toolkit.fluxcd.io/v2beta1
        kind: HelmRelease
        metadata:
          name: linkerd
          namespace: flux-system
        spec:
          values:
            podLabels: {}
      target:
        kind: HelmRelease
        name: linkerd
        namespace: flux-system
