apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dac
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 10m0s
  path: ./manifests/deployments/dac
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
