apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: dac-webhook
  annotations:
    cert-manager.io/inject-ca-from: flux-system/dac-webhook
webhooks:
  - name: dac-webhook.flux-system.svc
    failurePolicy: Fail # or Fail more information at https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#failure-policy
    sideEffects: None
    admissionReviewVersions: ["v1", "v1beta1", "v1beta2"]
    clientConfig:
      service:
        name: dac-webhook
        namespace: flux-system
        path: "/validate"
    rules:
      - operations: ["UPDATE"]
        apiGroups: ["apiextensions.k8s.io"]
        apiVersions: ["v1"]
        resources: ["customresourcedefinitions"]
        scope: "*"
