# apiVersion: kafka.strimzi.io/v1beta2
# kind: KafkaRebalance
# metadata:
#   name: kafka
#   namespace: kafka-operator
#   labels:
#     strimzi.io/cluster: kafka
# spec:
#   mode: add-brokers
#   brokers: [1]
# ---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: kafka-after-change-config
  namespace: kafka-operator
  labels:
    strimzi.io/cluster: kafka
  annotations:
    strimzi.io/rebalance-auto-approval: "true"
spec:
  mode: add-brokers
  brokers: [1, 2]