apiVersion: v1
kind: Pod
metadata:
  labels:
    run: kafka-consumer
  name: kafka-consumer
spec:
  containers:
  - args:
    - bash
    image: registry.localhost:5000/kafka:0.39.0-kafka-3.6.1
    imagePullPolicy: IfNotPresent
    name: kafka-consumer
    resources: {}
    stdin: true
    stdinOnce: true
    tty: true
    volumeMounts:
    - mountPath: /tmp/ca.p12
      subPath: ca.p12
      name: cluster-tls
    - mountPath: /tmp/client-scram.properties
      subPath: client-scram.properties
      name: properties
  volumes:
  - name: cluster-tls
    secret:
      secretName: kafka-cluster-ca-cert
  - name: properties
    configMap:
      name: client-scram-properties
