apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 10m0s
  path: ./manifests/strimzi-kafka-operator/0.39.0/kraft-3.6.1-sasl-ssl-single
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      AVAILABILITY_ZONES: '[ "us-east-2a" ]'
      CA_CERT_REPLICATE_TO_NAMESPACES: "default,kube-system"
