apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kafka
  namespace: flux-system
spec:
  dependsOn:
    - name: cert-manager
  interval: 10m0s
  # path: ./manifests/strimzi-kafka-operator/0.27.1
  path: ./manifests/strimzi-kafka-operator/0.39.0/kafka-zookeeper-3.6.1-sasl-ssl
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
