apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: accelbyte
  namespace: kafka-operator
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: scram-sha-512
  template:
    secret:
      metadata:
        annotations:
          replicator.v1.mittwald.de/replicate-to: ${SECRET_REPLICATE_TO_NAMESPACES:="justice"}
